#!/usr/bin/env node
// Daily standup: takes stock of recent publishing, flags issues, proposes today's sprint.
// Runs unattended. Output: a Markdown file in ops/standups/YYYY-MM-DD.md committed by CI.

import { promises as fs } from 'node:fs';
import path from 'node:path';
import matter from 'gray-matter';
import Anthropic from '@anthropic-ai/sdk';

const ARTICLES_DIR = path.resolve('src/content/articles');
const STANDUPS_DIR = path.resolve('ops/standups');
const ROADMAP = path.resolve('ops/ROADMAP.md');

function ymd(d = new Date()) {
  return d.toISOString().slice(0, 10);
}

async function loadRecent(days = 3) {
  const files = (await fs.readdir(ARTICLES_DIR).catch(() => [])).filter((f) => f.endsWith('.md'));
  const cutoff = Date.now() - days * 24 * 3600 * 1000;
  const out = [];
  for (const f of files) {
    const raw = await fs.readFile(path.join(ARTICLES_DIR, f), 'utf8');
    const { data, content } = matter(raw);
    const pub = Date.parse(data.pubDate);
    if (pub < cutoff) continue;
    out.push({ file: f, title: data.title, section: data.section, pub: data.pubDate, words: content.split(/\s+/).length });
  }
  return out.sort((a, b) => Date.parse(b.pub) - Date.parse(a.pub));
}

async function loadRoadmap() {
  return fs.readFile(ROADMAP, 'utf8').catch(() => '(roadmap not found)');
}

async function aiStandup({ recent, roadmap }) {
  const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
  const prompt = `You are the CEO of Real Daily Review writing the team's daily standup. Look at the recent activity and roadmap and produce a tight standup note.

Format (Markdown):
## Yesterday — what shipped
- Bullet list, one line each, factual

## Today — sprint focus
- 3-5 highest-leverage items from the roadmap. Tag (dev) (content) (growth) (monetization).

## Risks & blockers
- Anything that needs the shareholder's attention. Empty list is fine.

## Numbers to watch
- One line each — what we'd ideally see in tomorrow's standup.

Keep it under 300 words. No fluff.

RECENT ACTIVITY (last 3 days):
${JSON.stringify(recent, null, 2)}

ROADMAP:
${roadmap.slice(0, 4000)}`;

  const r = await client.messages.create({
    model: 'claude-haiku-4-5-20251001',
    max_tokens: 1200,
    temperature: 0.3,
    messages: [{ role: 'user', content: prompt }],
  });
  return r.content.filter((b) => b.type === 'text').map((b) => b.text).join('\n');
}

async function main() {
  await fs.mkdir(STANDUPS_DIR, { recursive: true });
  const date = ymd();
  const target = path.join(STANDUPS_DIR, `${date}.md`);

  // If today's standup already exists (we run on two cron crons for DST safety), skip
  if (await fs.stat(target).catch(() => null)) {
    console.log(`Standup ${date} already exists — skipping`);
    return;
  }

  const recent = await loadRecent(3);
  const roadmap = await loadRoadmap();
  const body = await aiStandup({ recent, roadmap });

  const file = `# Standup — ${date}\n\n${body}\n\n---\n_Auto-generated by ceo-standup._\n`;
  await fs.writeFile(target, file, 'utf8');
  console.log(`Wrote ${target}`);
}

main().catch((err) => { console.error(err); process.exit(1); });
